In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,3])

array([1, 2, 3, 4, 3])

In [4]:
arr=np.array([1,2,4,5,3])
arr

array([1, 2, 4, 5, 3])

In [5]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [6]:
a=[1,2,4.5,5,6.6]
a

[1, 2, 4.5, 5, 6.6]

In [7]:
a=[1,2,4.5,"hello"]
a

[1, 2, 4.5, 'hello']

In [8]:
a=np.array(a)
a

array(['1', '2', '4.5', 'hello'], dtype='<U32')

The above cell operation that is array is converted the values into strings there and print the strings

In [9]:
a=[1,2,4.5]
a

[1, 2, 4.5]

In [10]:
a=np.array(a)
a

array([1. , 2. , 4.5])

In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mat=np.array(a)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

This arange function will give a range of array of values as we can see

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [16]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

linspace() is used to create evenly spaced numbers between a starting value and an ending value

RANDOM GENRATIO FUNCTION

In [19]:
arr=np.random.rand(10)
arr

array([0.33183464, 0.18137583, 0.84742647, 0.46252132, 0.58116691,
       0.60412711, 0.63588621, 0.89104297, 0.63449731, 0.33287977])

In [20]:
np.random.randint(10,20,10)

array([19, 17, 17, 16, 18, 19, 19, 11, 12, 18])

In [21]:
arr=np.array([[1,2,4],[2,3,4],[4,5,3]])
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(5)

In [26]:
arr.sum()

np.int64(28)

In [27]:
np.sum(arr,axis=1)


array([ 7,  9, 12])

In [28]:
arr.mean()

np.float64(3.111111111111111)

In [29]:
arr.std()

np.float64(1.1967032904743342)

In [30]:

arr.argmax()

np.int64(7)

In [31]:

arr.argmin()

np.int64(0)

Reshaping and resizing

In [32]:
arr=np.arange(1,31,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

ARRAY INDEXING

In [34]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
array_slice=arr[3::2]
array_slice

array([4, 6, 8])

In [36]:
arr[4]

np.int64(5)

NUMPY INDEXING AND SLICING OF MATRIX

In [37]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:

slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [39]:

arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [40]:
slice = arr[3:]
slice

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
slice = arr[3,:]
slice

array([16, 17, 18, 19, 20])

BOOLEAN INDEXING

In [42]:

arr = np.arange(11,21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:

bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [44]:

arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

ARRAY OPERATIONS

In [45]:
a1=np.array([1,2,4,6,3,5])
a2=np.array([1,3,5,5,6,4])

In [46]:
a1+a2

array([ 2,  5,  9, 11,  9,  9])

In [47]:
a1-a2

array([ 0, -1, -1,  1, -3,  1])

In [48]:
a2-a1

array([ 0,  1,  1, -1,  3, -1])

In [49]:
a2*a1

array([ 1,  6, 20, 30, 18, 20])

In [50]:
a1/a2

array([1.        , 0.66666667, 0.8       , 1.2       , 0.5       ,
       1.25      ])

In [51]:
a1//a2

array([1, 0, 0, 1, 0, 1])

In [52]:
a1**a2

array([   1,    8, 1024, 7776,  729,  625])

In [53]:
a1+10

array([11, 12, 14, 16, 13, 15])

In [54]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
slice=a[:5]
slice

array([1, 2, 3, 4, 5])

In [57]:
slice=a[2:]
slice

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [58]:
slice=a[3:6]
slice

array([4, 5, 6])

In [59]:
slice=a[3:6]*10
slice

array([40, 50, 60])

In [61]:
a=np.arange(1,7,1)
a

array([1, 2, 3, 4, 5, 6])

In [63]:
b=a
b

array([1, 2, 3, 4, 5, 6])

In [64]:
b[0]=100
b

array([100,   2,   3,   4,   5,   6])

In [65]:
a

array([100,   2,   3,   4,   5,   6])

Shallow copy :where the list or array is copied from a to b then b has edited some value then also a has changed what is has changed the value ,so b and a are interconnected in deep copy

In [68]:
a=np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [70]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
b=a.copy()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Matric Operation

In [75]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [76]:
A

array([[1, 2],
       [3, 4]])

In [77]:
B

array([[5, 6],
       [7, 8]])

In [78]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

Advance Array Manipulation

Stacking Array

In [79]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,4])

In [81]:
np.vstack((a,b))


array([[1, 2, 3, 4],
       [2, 4, 6, 4]])

In [82]:
np.hstack((a,b))

array([1, 2, 3, 4, 2, 4, 6, 4])

In [83]:
np.column_stack((a,b))

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 4]])

Splitting array

In [85]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [91]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

EXERCISE QUESTIONS FOR PRACTISE

Valid Soduku

In [95]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [96]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [102]:
# Columns :[Age,Math Marks ,Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [108]:
#Get the shape of the matrix.
np.shape(data)


(5, 3)

In [112]:

#Find the average age of students.
np.average(data[:,0])

np.float64(18.4)

In [113]:
#Extract Math marks of all students.
data[:,1]



array([85, 92, 76, 65, 90])

In [114]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [124]:
#Get details of the student who scored more than 90 in Math.
maxi=data[:,1]>90
result=data[maxi]
result

array([[19, 92, 88]])

In [126]:

#Increase Math marks of all students by 5.
data[:,1]+5


array([90, 97, 81, 70, 95])

In [131]:
booli=data[:,0]<19
booli

array([ True, False,  True,  True, False])

In [132]:
data[booli]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [136]:
#Calculate the average marks in each subject (column-wise mean).
np.average(data,axis=0)

array([18.4, 81.6, 83.2])

In [ ]:
#Get data of students who scored at least 80 in both subjects.
maths=data[:,1]>80
maths



array([False,  True,  True, False,  True])

In [ ]:

science=data[:,2]>80
science

array([False,  True,  True, False,  True])

In [148]:
actual=(science & maths)
data[actual]

array([[19, 92, 88],
       [20, 90, 85]])

In [162]:

#Replace all Science marks < 75 with 0.
marks=data[:,2]<75
data[marks,2]=0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])