In [3]:
import numpy as np

In [4]:
# Create the array
arr=np.array([1,2,3,5])
arr

array([1, 2, 3, 5])

In [5]:
# Create numbers from 50 to 100.
arr=np.arange(0,51)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
# Create 15 evenly spaced numbers between 0 and 1.
arr=np.linspace(0,2,10)
arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [14]:
# Create a 3×4 matrix of zeros.
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
# Create a 2×6 matrix of ones.
arr=np.ones((2,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# Find shape of an array
np.shape(arr)

(3, 4)

In [ ]:
# Sum of Matrix
np.sum(arr)

np.int64(78)

In [25]:
# Finding dimenstion
np.ndim(arr)


2

In [30]:
# Without printing the array manually, determine how many rows and columns it has.
np.shape(arr)

(3, 4)

In [32]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
# Print the third row.
arr[2,:]

array([11, 12, 13, 14, 15])

In [34]:
# Print the fourth column.
arr[:,3]

array([ 4,  9, 14, 19, 24])

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr[]